#
# Development layer
#
FROM app:main

COPY files/dev /

RUN apk add --no-cache \
        php7-xdebug \
        php7-zlib \
;

# Install composer
COPY --from="composer:1.8.4" /usr/bin/composer /usr/bin/composer
RUN composer global require --quiet hirak/prestissimo \
 && composer clear-cache --quiet \
;

# Setup xdebug
RUN sed -i "/^xdebug\.remote_host\b/s/\S*$/$(ip route | head -n 1 | cut -d' ' -f3)/" /etc/php7/conf.d/xdebug.ini
