#
# Development layer
#
FROM app:main

COPY files/dev /

RUN apk add -U \
        php7-xdebug \
        php7-zlib \
 && rm -rf /var/cache/apk/* \
;

# Install composer
COPY --from="composer:1.8.4" /usr/bin/composer /usr/bin/composer
RUN composer global require --quiet hirak/prestissimo \
 && composer clear-cache --quiet \
;

# Setup xdebug
RUN HOST_IP="$(ip route | head -n 1 | cut -d' ' -f3)" \
 && sed -i "s/xdebug.remote_host=localhost/xdebug.remote_host=${HOST_IP}/g" /etc/php7/conf.d/xdebug.ini \
;
