imports:
    - { resource: ../config.d/ }

framework:
    profiler:
        only_exceptions: false
    router:
        resource: '%kernel.config_dir%/routing/routing_dev.yml'
        strict_requirements: true
    templating:
        engines: [ twig ]

monolog:
    handlers:
        application:
            channels:
                - !event
            level: debug
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            type: stream
        console:
            channels:
                - !console
                - !doctrine
                - !event
            process_psr_3_messages: false
            type: console

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

web_profiler:
    intercept_redirects: false
    toolbar: true
