imports:
    - { resource: ../config.d/ }

framework:
    profiler:
        only_exceptions: false
    router:
        resource: '%kernel.config_dir%/routing/routing_dev.yml'
        strict_requirements: true
    templating:
        engines: [ twig ]

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

web_profiler:
    intercept_redirects: false
    toolbar: true
