version: "2"

services:
    app:
        build: app
        image: app:main
        volumes: [ "../../:/srv" ]

    rabbitmq:
        image: rabbitmq:alpine
        volumes: [ /var/lib/rabbitmq ]

    redis:
        image: redis:alpine
        volumes: [ /data ]

    server:
        build: server
        image: app:server
        depends_on: [ app ]
        ports: [ 80 ]
        volumes_from: [ app ]
